"""empty message

Revision ID: 67c24b2eae7f
Revises: 
Create Date: 2019-09-27 13:32:54.282791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67c24b2eae7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ed_masterdata')
    op.drop_table('eddailydata')
    op.drop_table('edhoursref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edhoursref',
    sa.Column('id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    op.create_table('eddailydata',
    sa.Column('datereported', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('facility', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('presentation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage1presentation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage1withinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage2presentation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage2withinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage3presentation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage3withinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage4presentation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage4withinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage5presentation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('triage5withinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastupdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('etptotalpatient', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etptotalwithinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpadmittedpatient', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpadmittedwithinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpdischargedpatient', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpdischargedwithinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpteama', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpteamawithinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpteamb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('etpteambwithinbenchmark', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hospitaladmission', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('over24hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('facilityid', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('unallocatedpresentation', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('ed_masterdata',
    sa.Column('encounterid', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('facility', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.Column('arrivaldatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mrn', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('patientid', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('triagecategory', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('admitreason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('arrivalmode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('clinic', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('arrivaltodischarge', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('arrivaltotriage', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('seenbydoctor', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('seenbynurse', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('seenbytodecisiontoadmit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('decisiontoadmittoreadytodepart', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('readytodeparttodischarge', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('administrativegender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('visittype', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('triagedatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('first_decisiontoadmit', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('decisiontoadmitdatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('readytodepartdatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('dischargedatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('speciality', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('triagetoseenbydr', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('triagetoseenbynr', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('arrivaltodecisiontoadmit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('arrivaltoreadytodepart', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('seenbytodischarge', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('triagetodischarge', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('departmode', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('dischargedisposition', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('arrival_hr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('arrival_day', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('tracking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kpi_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('patientname', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updatingdatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('iswaiting', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('room', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('triagespecialty', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('arrivaltotreatmentstartinminutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('creatingdatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stayined', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dischargedispositionalias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('facilityname', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('seenby', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checkoutdatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('caldischargedatetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('los', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('isoverriddenbyeds', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('ismohextractdata', sa.CHAR(length=1), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
